#
# sudo mkdir -p /var/tmp/deb11pip-archive
# sudo mkdir -p /var/tmp/deb11pip-html
# sudo chown -R 1234:1234 /var/tmp/deb11pip-archive
# sudo chown -R 1234:1234 /var/tmp/deb11pip-html
#

services:
    weewx:
        image: deb11pip:latest
        container_name: deb11pip
        restart: unless-stopped
        volumes:
          - /var/tmp/deb11pip-archive:/home/weewx/weewx-data/archive
          - /var/tmp/deb11pip-html:/home/weewx/weewx-data/public_html

    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginxdeb11pip
        restart: unless-stopped
        ports:
          - "8701:80"
        volumes:
          - /var/tmp/deb11pip-html:/usr/share/nginx/html

