
version: "2"

services:
    weewx:
        image: deb11pip:latest
        container_name: deb11pip
        restart: unless-stopped
        volumes:
          - ./tmpdata/archive:/home/weewx/weewx-data/archive
          - ./tmpdata/html:/home/weewx/weewx-data/public_html

    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginxdeb11pip
        restart: unless-stopped
        ports:
          - "8701:80"
        volumes:
          - ./tmpdata/html:/usr/share/nginx/html:ro

