
version: "2"

services:
    weewx:
        image: rocky8pkg:latest
        container_name: rocky8
        restart: unless-stopped
        volumes:
        - ./tmpdata/html:/var/www/html/weewx

    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginxrocky8
        restart: unless-stopped
        ports:
        - "8811:80"
        volumes:
        - ./tmpdata/html:/usr/share/nginx/html
