
version: "2"

services:
    weewx:
        image: rocky9pip:latest
        container_name: rocky9
        restart: unless-stopped
        volumes:
        - ./tmpdata/archive:/home/weewx/weewx-data/archive
        - ./tmpdata/html:/home/weewx/weewx-data/public_html

    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginxrocky9
        restart: unless-stopped
        ports:
        - "8901:80"
        volumes:
        - ./tmpdata/html:/usr/share/nginx/html

